services:
  db:
    image: postgres:latest
    container_name: pg-db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: pgdb
    volumes:
      - ./backup:/docker-entrypoint-initdb.d
    ports:
      - 397:5432
    restart: always
  web:
    image: golang:latest
    container_name: go-app
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      DB_HOST: db
      DB_USER: test
      DB_PASSWORD: test
      DB_NAME: pgdb
    depends_on:
      - db
    ports:
      - 3710:8080
    restart: always
    command: go run /app/.
